import { generateObject } from "ai";
import { z } from "zod";
import {
  MODERATION_PROMPT_VERSION,
  MODERATION_SYSTEM_PROMPT_V1,
} from "@/lib/ai/prompts";

const MODEL_MODERATION = "anthropic/claude-haiku-4.5";

const verdictSchema = z.object({
  safe: z.boolean(),
  reason: z.string().max(200).optional(),
});

export type ModerationVerdict =
  | { safe: true }
  | { safe: false; reason: string };

export type ModerationContext = "user_input" | "ai_output";

/**
 * Pre/post-display content moderation. Every AI generation MUST pass this
 * before storage or display (see CLAUDE.md). Returns a verdict; caller
 * decides what to do on UNSAFE (reject vs. retry vs. queue for review).
 */
export async function moderateText(
  text: string,
  context: ModerationContext
): Promise<ModerationVerdict & { promptVersion: string }> {
  const trimmed = text.trim();
  if (!trimmed) return { safe: true, promptVersion: MODERATION_PROMPT_VERSION };

  const userPrompt = `Classify the following ${
    context === "user_input"
      ? "text written by a kid creator"
      : "text generated by an AI character system"
  }. Respond with the JSON verdict.

Text:
"""
${trimmed}
"""`;

  const { object } = await generateObject({
    model: MODEL_MODERATION,
    schema: verdictSchema,
    system: MODERATION_SYSTEM_PROMPT_V1,
    prompt: userPrompt,
  });

  if (object.safe) {
    return { safe: true, promptVersion: MODERATION_PROMPT_VERSION };
  }
  return {
    safe: false,
    reason: object.reason ?? "That doesn't quite fit here — try something else.",
    promptVersion: MODERATION_PROMPT_VERSION,
  };
}
